import urllib.request
import urllib.error
import json
import time
import sys

def test_sync_api():
    print("========================================")
    print("  E2E-08: Offline -> Online Sync Cycle  ")
    print("========================================")
    
    url = "http://localhost:3000/v1/sync"
    
    # Simulate 5 offline logs generated by the mobile app
    payload = {
        "logs": [
            {"id": "LOG_1001", "userId": "EMP_001", "timestamp": str(int(time.time()*1000)), "status": "SUCCESS", "livenessResult": "PASS", "location": "13.5 N, 79.9 E"},
            {"id": "LOG_1002", "userId": "EMP_002", "timestamp": str(int(time.time()*1000)), "status": "SUCCESS", "livenessResult": "PASS", "location": "13.5 N, 79.9 E"},
            {"id": "LOG_1003", "userId": "EMP_003", "timestamp": str(int(time.time()*1000)), "status": "SUCCESS", "livenessResult": "PASS", "location": "13.5 N, 79.9 E"},
            {"id": "LOG_1004", "userId": "EMP_004", "timestamp": str(int(time.time()*1000)), "status": "FAIL", "livenessResult": "FAIL", "location": "13.5 N, 79.9 E"},
            {"id": "LOG_1005", "userId": "EMP_005", "timestamp": str(int(time.time()*1000)), "status": "SUCCESS", "livenessResult": "PASS", "location": "13.5 N, 79.9 E"}
        ]
    }
    
    data = json.dumps(payload).encode('utf-8')
    req = urllib.request.Request(url, data=data, headers={'Content-Type': 'application/json'})
    
    try:
        start_time = time.time()
        response = urllib.request.urlopen(req)
        end_time = time.time()
        
        resp_data = json.loads(response.read().decode('utf-8'))
        
        print(f"Status Code: {response.getcode()}")
        print(f"Response: {resp_data}")
        print(f"Latency: {(end_time - start_time)*1000:.2f} ms")
        
        if response.getcode() == 202 and len(resp_data.get('synced_ids', [])) == 5:
            print("\n✅ PASS: Successfully synced 5 records to Mock AWS API Gateway.")
        else:
            print("\n❌ FAIL: Did not sync records correctly.")
            sys.exit(1)
            
    except Exception as e:
        print(f"\n❌ FAIL: Error calling sync API: {e}")
        sys.exit(1)

    print("\nVerifying DB Status...")
    try:
        status_req = urllib.request.urlopen("http://localhost:3000/v1/sync_status")
        status_data = json.loads(status_req.read().decode('utf-8'))
        print(f"Total Records in DB: {status_data['total_records']}")
        
        if int(status_data['total_records']) >= 5:
            print("✅ PASS: Database successfully persisted synced logs.")
        else:
            print("❌ FAIL: Database missing records.")
    except Exception as e:
        print(f"❌ FAIL: {e}")

if __name__ == "__main__":
    test_sync_api()
